/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:77d624a4-a718-4e4e-bfd2-f6d0972087c0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_haUfcf6DN",
    "aws_user_pools_web_client_id": "1kl0q0e9b4doku9t29lfaf8iku",
    "oauth": {}
};


export default awsmobile;
