/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3b153d94-e45c-4e6b-a3e3-08c3bc0e303d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ObAggfa3B",
    "aws_user_pools_web_client_id": "56g16r9cjcofgai7fjofokkqpc",
    "oauth": {
        "domain": "tasteitf60714dd-f60714dd-develop.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/dashboard/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
