/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b2abbc9b-7b11-4533-b82b-88bb5bf01de9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9JU8GaBbl",
    "aws_user_pools_web_client_id": "37og0b6dbb6ldm08redd58rhms",
    "oauth": {}
};


export default awsmobile;
