export { default as Features } from './Features'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as HowItWorks } from './HowItWorks'
export { default as Proposal } from './Proposal'
export { default as Team } from './Team'
export { default as Top } from './Top'
